### ISSUE TITLE
Giger Counter has no localized description

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#15]
![image](https://user-images.githubusercontent.com/29014194/166138645-d833d990-6e19-4ecd-8dc0-6aa304f8d474.png)

**Comment by TF2V** [comment]
This issue is resolved by 56dac6554521cfdd124b55db612e7e925c2ba82c.

Really odd how TF2 also defines the description in their items_game script, yet it too is unused.

**Comment by conneath** [comment]
still not fixed

**Comment by TF2V** [comment]
Is it still showing a fake localization?

TF2 declared a description, but never used it. That's why that commit removes the declaration for a description.

**Comment by conneath** [comment]
> Is it still showing a fake localization?

yup

![image](https://user-images.githubusercontent.com/29014194/167284839-3f500308-312a-49d1-bb50-f2241c907c5f.png)
