### ISSUE TITLE
Wearable type items do not seem to exist

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#17]
wearing stuff like the Gunboats, Mantreads etc. doesn't have any effect, having this printed to the console
```
Attempted to create unknown entity type tf_wearable_soldier!
NULL Ent in GiveNamedItem!
```
or if you're playing Demoman
```
Attempted to create unknown entity type tf_wearable_demoman!
NULL Ent in GiveNamedItem!
```

**Comment by TF2V** [comment]
Fixed by commit 7a476e33e665cb22beab6cf5224758d7fa157677.
