### ISSUE TITLE
Changes to loadout dont appear/reset

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#18]
this started happening as soon as i installed the new build
i change my loadout, everything looks fine, but opening the loadout menu again or changing to another class and changing back doesn't show these changes, they apply just fine though

**Comment by conneath** [comment]
example video:
https://user-images.githubusercontent.com/29014194/166255726-1145ef1f-ec93-4fc1-b32d-d8afce771e6a.mp4

**Comment by conneath** [comment]
this also makes choosing multiple non stock weapons in a single loadout impossible, because it keeps resetting the last weapon you selected back to stock

**Comment by conneath** [comment]
this makes it rather annoying to use multiple weapons, you have to do it all in one opening of the loadout menu; opening, switching your primary, closing, then opening again & switching your secondary will only make the change to your secondary apply

**Comment by conneath** [comment]
this doesn't happen on a debug build for some reason

**Comment by conneath** [comment]
its a little bit better on loadout screens that have a PDA slot (engineer and spy) but it still resets when you reopen it (doesn't reset when you go back to the menu after choosing a weapon though

**Comment by Deathreus** [comment]
Can't reproduce
