### ISSUE TITLE
mini sentries dont start with 50/100 HP

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#33]
instead of starting with 100HP or 50HP they start off with 1 HP like a normal sentry gun

**Comment by TF2V** [comment]
Never knew the mini-sentry started with more health.
When did the mini-sentry change from 50HP starting health to 100HP starting health?

**Comment by Menoly12** [comment]
They changed it to 50 health during gunmetal and prior to that it was at 100 though idk how long it was at 100% health for or if it was always like that

**Comment by Menoly12** [comment]
![image](https://user-images.githubusercontent.com/61127054/167460871-4f7a3b79-788d-487a-a58d-cb3594fb5252.png)

**Comment by Menoly12** [comment]
looked into it a bit more it was always 100% before going to 50% during gun metal 
![image](https://user-images.githubusercontent.com/61127054/167463642-6831bec7-da12-426f-b2ae-f3713770f22c.png)
![image](https://user-images.githubusercontent.com/61127054/167463698-74bf79aa-da5b-4377-a970-34bdbe6bc999.png)

**Comment by TF2V** [comment]
Interesting, none of these are on the patch notes for the Sentry Gun itself, but are on the Gunslinger's patch notes instead. Explains why I never found them.

I'll push this implementation when it's ready.

**Comment by conneath** [comment]
https://conneath.gq/repo/minisentry.mp4
mini sentry doesn't do anything after being built if tf2v_use_new_minibuildings is turned off

**Comment by TF2V** [comment]
I believe that has to do with the fact it checks the health of the buildable compared to the max health as it builds, then calculates out the amount it's supposed to heal.
My guess is that since the starting health is also the max health, this gets zero'd out which in turn, causes the construction time to be infinity (health/∆health = health/0 == Undefined)

**Comment by conneath** [comment]
no more issues it seems
