### ISSUE TITLE
old "disguised as a <TEAM> <CLASS>" text

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#39]
![image](https://user-images.githubusercontent.com/29014194/167284655-5636bbfc-3a93-4710-a6fa-42a27dd38084.png)
this is probably a leftover from the 2008 build
maybe switch it showing with a client convar or something

**Comment by Deathreus** [comment]
I'm not even sure where that's drawing from

**Comment by TF2V** [comment]
I remember seeing this previously, it's in `tf_hud_disguise_status.cpp`
The `tf2v_enable_disguise_text` convar should enable/disable this.

**Comment by conneath** [comment]
i didn't even know there was a convar for that, maybe should default to it being off, it looks weird combined with the new disguise UI
