### ISSUE TITLE
"get on point" keeps being repeated when attacking on point

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#40]
this should only get said occasionally but it happens always
https://conneath.gq/repo/standonthe.mp4

**Comment by TF2V** [comment]
From my initial look, this is coming from an automatic response rule TF2 added later on (`DefendOnThePoint<class>`) that activates when you're firing on a friendly control point. My search on older talker files didn't return this rule, and only returned the similar`PlayerHelpCapture2<class>` which is the response rule when you ask for help while on a point.
I think what's happening is that the criteria for not nagging the player in the response rule isn't there, and it must have been hard coded to either not nag the player or add a cooldown to auto responses.
