### ISSUE TITLE
Ambassador can't headshot

### ISSUE THREAD

**Issue by conneath** [TF2V/TF2Vintage#60]

**Comment by TF2V** [comment]
Check your `tf2v_use_new_ambassador` value in the console. 0 gives minicrits, 1 is the standard crits and 2 is crit/minicrit falloff.

This one appears to be an older weapon, so the code for it could use some improvements.

**Comment by TF2V** [comment]
[7b0e108](https://github.com/TF2V/TF2Vintage/commit/7b0e1080d6f2cfa1467079cf7df633c6dc06e250) Is a quick rewrite of the content that is already there. Also fixes the fact the TF2V Ambassador has a longer firing cooldown than the Retail TF2 variant.

**Comment by conneath** [comment]
i remember testing all values of tf2v_use_new_ambassador and couldn't headshot (was testing with someone else and he couldn't headshot either)
i will try this again later and confirm if this issue is still here or not

**Comment by conneath** [comment]
also sorta unrelated but i think the descriptions of tf2v convars should use text from server_extra.cfg, most of the time that has much more info and the convar description doesn't, its much more faster to just type the convar than to open a text file

**Comment by Deathreus** [comment]
Can't reproduce, assuming fixed
