### ISSUE TITLE
rebuild not working

### ISSUE THREAD

**Issue by engineergamingistaking** [TF2V/TF2Vintage#7]
when trying to rebuild it says that:	'g_Script_vscript_init': undeclared identifier, 'g_Script_vscript_client': undeclared identifier, and 'g_Script_vscript_server': undeclared identifier.

**Comment by TF2V** [comment]
Can you give more details of the error? How you compiled the solution, and what you're using to rebuild it?
Try running the "createtf2vintage" file located in src, and then use Visual Studio 2015 or higher.

**Comment by yeetbio** [comment]
the error is saying that something is wrong with the script line so it might be misspelled or something, and I'm using visual studio 2015 to rebuild the solution

**Comment by yeetbio** [comment]
how to compile

**Comment by engineergamingistaking** [comment]
I'm using visual studio 2015 and i have compiled the solution but it still does not work

**Comment by TF2V** [comment]
I'm having trouble trying to reproduce this, can I get more information about your OS and how you're trying to build this?
I tested this using `Windows 10 Pro 21H2`, on `Visual Studio 2019` running in the default `Microsoft Studio 2015 - Windows XP (v140_xp)` toolset and was able to make a successful build.
My procedure was:
1. Download the ZIP of the TF2Vintage 3.6 repository at a clean location.
2. Extract it, navigate to the `src` folder and run `createtf2vintage.bat` to build a solution.
3. When built, load `TF2vintage.sln` into Visual Studio.
4. Once loaded in Visual Studio, press Build->Build Solution and wait for the solution to compile.
![Output](https://user-images.githubusercontent.com/29987895/159147696-0c3005e1-b205-43e8-9361-e820accbed81.PNG)

**Comment by engineergamingistaking** [comment]
i have windows 10 pro 21H1 and I'm building this using visual c++ toolset

**Comment by yeetbio** [comment]
also, how do i download at a clean location

**Comment by engineergamingistaking** [comment]
also how to install Microsoft Studio 2015 - Windows XP (v140_xp) toolset

**Comment by TF2V** [comment]
> i have windows 10 pro 21H1 and I'm building this using visual c++ toolset

As long as you have Visual Studio 2015 or newer, you can get the correct toolset for compiling.

> also, how do i download at a clean location

By a "clean location" I am simply referring to an area that is isolated from the rest of my development files, as if starting from a fresh download.

> also how to install Microsoft Studio 2015 - Windows XP (v140_xp) toolset


When you install or modify your copy of Visual Studio, it will give you options on what toolsets you want to install. One of them will be named `MSVC v140 - VS 2015 C++ Build Tools` which is the required toolset for TF2V.
Just to double check this, I installed `Visual Studio 2022` and selected the `Desktop Development with C++` mode and only the `MSVC v140 - VS 2015 C++ Build Tools (v14.00)` optional toolset. It too compiled without error.
![Compile 2022](https://user-images.githubusercontent.com/29987895/159175631-399466e2-dc55-4158-8197-e782f805f6a4.PNG)
Edit: You can get there quickly by `Tools->Get Tools and Features...` in the Visual Studio app.

**Comment by TF2V** [comment]
Have you been able to compile a build yet? I have now had other separate users report being able to make a successful build of the most recent version.

If I do not receive a response by the end of the week, I will assume this issue is resolved.

**Comment by TF2V** [comment]
Closed because it has been almost four weeks without a reply.

Since this post, the workflows for the project have been expanded to an all in one solution. The tf2vintage action now passes when both Windows and Linux pass compiling.

[![tf2vintage](https://github.com/TF2V/TF2Vintage/actions/workflows/tf2vintage.yml/badge.svg)](https://github.com/TF2V/TF2Vintage/actions/workflows/tf2vintage.yml)
