### ISSUE TITLE
Visual Studio 2022 compile support

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [TF2V/TF2Vintage#78]
Title

**Comment by Deathreus** [comment]
It already compiles under 2022

**Comment by FriskTheFallenHuman** [comment]
...it fails to compile in vs2022 because of `_msize_base` changed in one of the windows sdk versions

**Comment by TF2V** [comment]
Seems to be missing the following dependencies as well.
```
Parsing: client_tf2vintage.vpc
WARNING: File '..\..\public\steam\steam_api.h' does not exist. Not adding to project.
Saving... Project: 'Client (TF)' File: 'client_tf2vintage.vcxproj'

Parsing: server_tf2vintage.vpc
WARNING: File '..\..\public\steam\steam_api.h' does not exist. Not adding to project.
Saving... Project: 'Server (TF)' File: 'server_tf2vintage.vcxproj'

Parsing: vscript.vpc
WARNING: File '..\thirdparty\luajit\src\luajit.c' does not exist. Not adding to project.
WARNING: File '..\thirdparty\luajit\src\lauxlib.h' does not exist. Not adding to project.
WARNING: File '..\thirdparty\luajit\src\lualib.h' does not exist. Not adding to project.
WARNING: File '..\thirdparty\luajit\src\lua.h' does not exist. Not adding to project.
WARNING: File '..\thirdparty\luajit\src\luaconf.h' does not exist. Not adding to project.
WARNING: File '..\thirdparty\luajit\src\luajit.h' does not exist. Not adding to project.
Saving... Project: 'VScript' File: 'vscript.vcxproj'
```

**Comment by FriskTheFallenHuman** [comment]
not sure if is related to my cmake branch or vs2022 but i got a crash at strncpy.asm
![image](https://user-images.githubusercontent.com/12750944/197419062-f7670b97-103c-497a-bd03-1ae8fdb56124.png)
from reading the stack trace it happens at:
![image](https://user-images.githubusercontent.com/12750944/197419252-43cad955-d658-4153-85f8-11b042940abb.png)
This is latest code pullet.

**Comment by FriskTheFallenHuman** [comment]
> Seems to be missing the following dependencies as well.
> 
> ```
> Parsing: client_tf2vintage.vpc
> WARNING: File '..\..\public\steam\steam_api.h' does not exist. Not adding to project.
> Saving... Project: 'Client (TF)' File: 'client_tf2vintage.vcxproj'
> 
> Parsing: server_tf2vintage.vpc
> WARNING: File '..\..\public\steam\steam_api.h' does not exist. Not adding to project.
> Saving... Project: 'Server (TF)' File: 'server_tf2vintage.vcxproj'
> 
> Parsing: vscript.vpc
> WARNING: File '..\thirdparty\luajit\src\luajit.c' does not exist. Not adding to project.
> WARNING: File '..\thirdparty\luajit\src\lauxlib.h' does not exist. Not adding to project.
> WARNING: File '..\thirdparty\luajit\src\lualib.h' does not exist. Not adding to project.
> WARNING: File '..\thirdparty\luajit\src\lua.h' does not exist. Not adding to project.
> WARNING: File '..\thirdparty\luajit\src\luaconf.h' does not exist. Not adding to project.
> WARNING: File '..\thirdparty\luajit\src\luajit.h' does not exist. Not adding to project.
> Saving... Project: 'VScript' File: 'vscript.vcxproj'
> ```

also, angel script refuses to build under vs2022 it compiles fine if you fix the submodule issue but it shats itself on Linking again not sure if it's my fault at my end, oh also vscript expects angelscript.lib to be compile yet there's no such lib under the lib folder I think i mentioned that #74 the read doesn't state what's required to build

EDIT: even if you build angelscript, it will still complain about Linking errors

**Comment by Deathreus** [comment]
> ...it fails to compile in vs2022 because of `_msize_base` changed in one of the windows sdk versions

That has nothing to do with version, and it was also addressed a couple months ago

**Comment by FriskTheFallenHuman** [comment]
> > ...it fails to compile in vs2022 because of `_msize_base` changed in one of the windows sdk versions
> 
> That has nothing to do with version, and it was also addressed a couple months ago

It actually is
![image](https://user-images.githubusercontent.com/12750944/197425376-cda38a53-8295-478b-8c1f-b6db1e079b01.png)

**Comment by Deathreus** [comment]
Already did that, but still has nothing to do with version of Visual Studio
