### ISSUE TITLE
Can't Compile Under Visual Studio 2022

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [TF2V/TF2Vintage#90]
title, i basically get this error in cdll_client_init.cpp `error C2440: '=': cannot convert from '_Other' to '_Ty'`

**Comment by GuestSneezeOSDev** [comment]
do you have Visual Studio 2013 installed?

**Comment by Juesto** [comment]
works fine with visual studio 2015 here

**Comment by TF2V** [comment]
TF2V is in the process of being rebuilt to work on Visual Studio 2015, much like other TF2 Sourcemods. The requirement of 2022 is currently obsolete at this time.

**Comment by Juesto** [comment]
we're using the tf2 leak vpc executable which also has 2015 support
vpc sources are leaked as well
@GuestSneezeOSDev
